### PR TITLE
Feature/german

### LINKED ISSUE #202: [I18N][GER] Translate the 99 catfacts into German
### Description
Translate the 99 catfacts into german.

## Acceptance Criteria
- [ ] Translate the 99 facts from the other [models](https://github.com/wh-iterabb-it/meowfacts/blob/main/src/models/localization/eng-US.js) and translate those into German.

### PR DESCRIPTION
**Pull request by nickcrisci**
Closes #202

### Description of Changes for Review:
Added the translation of the 99 Catfacts in [models](https://github.com/wh-iterabb-it/meowfacts/blob/main/src/models/localization/eng-US.js) into german.
Furthermore I added the case statement to the `src\models\facts.js` File and ISO Strings to the corresponding Lists in `src/middleware.js`

### Changes to be commited
- [x] the 99 german catfacts in `src\models\localization\de-DE.js`
- [x] updated `src\models\facts.js` with the case statement for the german [i18n]
- [x] updated `src/middleware.js` with ISO strings for the german [i18n]

### CODE REVIEW

**Comment by switchhalt** [comment]
CC @BeauBouchard

**Comment by BeauBouchard** [comment]
> CC @BeauBouchard

going to make a small change to the branch if i can. 

```
npm run test:lint:fix
```
should be added to our documentation for new contributors. Also we can make the lint run without running people's branch code, so maybe we can change our workflowpipeline.

**Comment by BeauBouchard** [comment]
@nickcrisci 
thank you so much for making this contribution, Amazing work and you allowed us to have a whole language of results :D !!!

We will be reviewing this and getting it in as soon as we can.

**Comment by switchhalt** [comment]
@BeauBouchard solving the linting in a separate branch then merging.

**Review by switchhalt — APPROVED** [review]

**Pull request merged**
